/* ==========================================================================
   KALAN OS 5.1  --  game manifest
   --------------------------------------------------------------------------
   THIS IS THE ONLY FILE YOU NEED TO EDIT TO ADD A GAME.

   Add one object to GAMES below and it appears on the desktop, in the Start
   menu, and in the taskbar automatically. No other file needs to change.

   Sprite format: 16 rows of 16 characters, top to bottom.
     '.' = transparent
     everything else = a key from PALETTE below

   Palette keys:
     0 black        1 white        2 light grey   3 grey      4 dark slate
     r red          R dark red     o orange       y yellow    Y dark yellow
     g green        G dark green   c cyan         C dark cyan b blue
     B dark blue    p purple       P dark purple  m brown     M dark brown
     s silver
   ========================================================================== */

window.PALETTE = {
  '0': '#0d0d16', '1': '#f2f2f7', '2': '#b8b8c8', '3': '#6b6b85', '4': '#2a2a3d',
  'r': '#ef4444', 'R': '#991b1b', 'o': '#fb923c', 'y': '#facc15', 'Y': '#a16207',
  'g': '#4ade80', 'G': '#15803d', 'c': '#22d3ee', 'C': '#0e7490', 'b': '#60a5fa',
  'B': '#1d4ed8', 'p': '#c084fc', 'P': '#7e22ce', 'm': '#b45309', 'M': '#78350f',
  's': '#94a3b8',
};

window.GAMES = [
  {
    id: 'puzzle-time-attack',
    title: 'Puzzle Time Attack',
    blurb: 'Race the clock through escalating brain teasers.',
    category: 'Puzzle',
    accent: '#facc15',
    url: 'https://puzzle-time-attack.vercel.app',
    sprite: [
      '................',
      '......0000......',
      '.....0yyyy0.....',
      '....0yy00yy0....',
      '...0yyy00yyy0...',
      '...0yyy00yyy0...',
      '..0yyyy00yyyy0..',
      '..0yyyy00000y0..',
      '..0yyyy00rr0y0..',
      '..0yyyyyyyryy0..',
      '...0yyyyyyyyr0..',
      '...0yyyyyyyy0...',
      '....0yyyyyy0....',
      '.....0yyyy0.....',
      '......0000......',
      '................',
    ],
  },
  {
    id: 'conways-climber',
    title: "Conway's Climber",
    blurb: 'A colony of cells climbing the grid, one generation at a time.',
    category: 'Simulation',
    accent: '#4ade80',
    url: 'https://conways-climber.vercel.app',
    sprite: [
      '................',
      '................',
      '................',
      '................',
      '.0000.0000.0000.',
      '.0440.0gg0.0440.',
      '.0440.0gg0.0440.',
      '.0000.0000.0000.',
      '................',
      '.0000.0000.0000.',
      '.0440.0440.0440.',
      '.0440.0440.0440.',
      '.0000.0000.0000.',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'neon-fall',
    title: 'Neon Fall',
    blurb: 'Blocks fall fast. Stack them, clear the lines, survive.',
    category: 'Arcade',
    accent: '#c084fc',
    url: 'https://neon-fall.vercel.app',
    sprite: [
      '................',
      '.c..............',
      '................',
      '................',
      '....11111111....',
      '....0pppppp0....',
      '.c..0pppppp0..c.',
      '....0pppppp0....',
      '.cc.0pppppp0..c.',
      '....0pppppp0....',
      '.c..0pppppp0..c.',
      '....0pppppp0....',
      '................',
      '.cccccccccccccc.',
      '..000000000000..',
      '................',
    ],
  },
  {
    id: 'simple-sandbox',
    title: 'Simple Sandbox',
    blurb: 'A tidy physics box. Spawn, drop, break everything.',
    category: 'Sandbox',
    accent: '#fb7185',
    url: 'https://simple-sandbox.vercel.app',
    sprite: [
      '................',
      '................',
      '................',
      '....0gggggg0....',
      '....0gggggG0....',
      '....0gggggG0....',
      '....00000000....',
      '...0yyyyyyyy0...',
      '...0yyyyyyyY0...',
      '...0yyyyyyyY0...',
      '...0000000000...',
      '..0rrrrrrrrrr0..',
      '..0rrrrrrrrrR0..',
      '..0rrrrrrrrrR0..',
      '..000000000000..',
      '................',
    ],
  },
  {
    id: 'kcl-two',
    title: "Kalan's Coding Language",
    blurb: 'A tiny programming language you can actually write and run.',
    category: 'Tool',
    accent: '#22d3ee',
    url: 'https://kcl-two.vercel.app',
    sprite: [
      '................',
      '................',
      '0000000000000000',
      '.0bbbbbbbbbbbb0.',
      '.0bbbbbbbbbbbb0.',
      '.00000000000000.',
      '.04444444444440.',
      '.0g.44444444440.',
      '.0gg44444444440.',
      '.0g.4cc44444440.',
      '.04444444444440.',
      '.04444444444440.',
      '.04444444444440.',
      '0000000000000000',
      '................',
      '................',
    ],
  },
  {
    id: 'squishy-ball-runner',
    title: 'Squishy Ball Runner',
    blurb: 'A bouncy ball with places to be. Mostly past them.',
    category: 'Arcade',
    accent: '#fb923c',
    url: 'https://squishy-ball-runner.vercel.app',
    sprite: [
      '................',
      '................',
      'cc..............',
      '................',
      '.cc.............',
      '................',
      '....00000000....',
      'cc.0oooooooo0...',
      '...0oooooooooo0.',
      '...01ooooooooo0.',
      '.cc0ooooooooo0..',
      '...0ooooooooo0..',
      '....00000000....',
      '4444444444444444',
      '................',
      '................',
    ],
  },
  {
    id: 'mc-textures',
    title: "Minecraft's Textures",
    blurb: 'Browse the whole block texture library, block by block.',
    category: 'Viewer',
    accent: '#84cc16',
    url: 'https://mc-textures.vercel.app',
    sprite: [
      '................',
      '......gggg......',
      '....gggggggg....',
      '..gggggggggggg..',
      '.gggggggggggggg.',
      '.0mmmmmmMMMMMM0.',
      '.0m0mm0mM0MM0M0.',
      '.0mmmmmmMMMMMM0.',
      '.0m0mmm0M0MMM0..',
      '.0mmmmmmMMMMMM0.',
      '.0m0mmmmM0MMM0..',
      '.0mmmmmmMMMMMM0.',
      '.0mmmmmmMMMMMM0.',
      '.00000000000000.',
      '................',
      '................',
    ],
  },
  {
    id: 'kalansplane',
    title: "Kalan's Plane",
    blurb: 'A little plane over open country and a lot of sky.',
    category: 'Arcade',
    accent: '#38bdf8',
    url: 'https://kalansplane.vercel.app',
    sprite: [
      '................',
      '......0000......',
      '......c112......',
      '......c112......',
      '......c112......',
      '......c112......',
      '..000011110000..',
      '..011111111110..',
      '..001111111100..',
      '......c112......',
      '......c112......',
      '....01111110....',
      '....00000000....',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'mazeofballs',
    title: 'Maze of Balls',
    blurb: 'Roll the ball through the green walls. They do not move.',
    category: 'Puzzle',
    accent: '#34d399',
    url: 'https://mazeofballs.vercel.app',
    sprite: [
      'gggggggggggggggg',
      'g...g.......g..g',
      'g.g.g.ggggg.g.g.',
      'g.g.g.....g.g.g.',
      'g.g.ggggg.g.g.g.',
      'g.g.......g.g.g.',
      'g.ggggggg.g.g.g.',
      'g.........g.g.g.',
      'g.ggggggggg.g.g.',
      'g...........g.g.',
      'g.ggggggggggg.g.',
      'gc.............g',
      'g.ggggggggggg.g.',
      'g..............g',
      'g.ggggggggggg.g.',
      'g..............g',
    ],
  },
  {
    id: 'kalanski',
    title: "Kalan's Ski",
    blurb: 'Carve the slope, clip the gates, beat the clock.',
    category: 'Arcade',
    accent: '#60a5fa',
    url: 'https://kalanski.vercel.app',
    sprite: [
      '...........rrrr.',
      '......00....r...',
      '.....0ss0...r...',
      '.....0ss0...r...',
      '....00oo00..r...',
      '....0oooo0..r...',
      '....0b00b0..r...',
      '....221111111111',
      '.....22111111111',
      '......2211111111',
      '.......221111111',
      '........22111111',
      '.........2211111',
      '..........221111',
      '...........22111',
      '............2211',
    ],
  },
  {
    id: 'kalansea',
    title: "Kalan's Sea",
    blurb: 'An endless ocean. Sail it, name things, get lost.',
    category: 'Ambient',
    accent: '#a78bfa',
    url: 'https://kalansea.vercel.app',
    sprite: [
      '................',
      '......yyyy......',
      '.....yyyyyy.....',
      '....yyyyyyyy....',
      '....yyyyyyyy....',
      '.....ooyyoo.....',
      '......oooo......',
      '.11bbbb..11bbbb.',
      '.bbbbbbbbbbbbbb.',
      '.cccccccccccccc.',
      '..11bbbb..11bbb.',
      '..bbbbbbbbbbbb..',
      '..cccccccccccc..',
      '.11bbbb..11bbbb.',
      '.bbbbbbbbbbbbbb.',
      '.cccccccccccccc.',
    ],
  },
  {
    id: 'cardforge3d',
    title: 'Card Forge 3D',
    blurb: 'Crack open packs, pull the foils, forge the ultimate deck.',
    category: 'Cards',
    accent: '#fbbf24',
    url: 'https://cardforge3d.vercel.app',
    sprite: [
      '................',
      '..000000000000..',
      '..0oooooooooo0..',
      '..000000000000..',
      '..0pppppppppp0..',
      '..0p11111111p0..',
      '..0p1yyyyyy1p0..',
      '..0p1y1111y1p0..',
      '..0p1y1cc1y1p0..',
      '..0p1y1111y1p0..',
      '..0p1yyyyyy1p0..',
      '..0p11111111p0..',
      '..0pppppppppp0..',
      '..000000000000..',
      '................',
      '................',
    ],
  },
];
